using Kafka.Application.Dto;
using Kafka.Domain.Entities;

namespace Kafka.Application.Mapper
{
    public static class BcpPartOrderMapper
    {
        public static List<BcpPartOrder> ToEntity(
            List<BcpPartOrderDto> dtos)
        {
            return dtos.Select(dto => new BcpPartOrder
            {
                Id = dto.Id,
                OwnerId = dto.OwnerId,
                IsDeleted = dto.IsDeleted,
                Name = dto.Name,
                CurrencyIsoCode = dto.CurrencyIsoCode,
                RecordTypeId = dto.RecordTypeId,
                CreatedDate = dto.CreatedDate,
                CreatedById = dto.CreatedById,
                LastModifiedDate = dto.LastModifiedDate,
                LastModifiedById = dto.LastModifiedById,
                SystemModstamp = dto.SystemModstamp,
                LastActivityDate = dto.LastActivityDate,
                LastViewedDate = dto.LastViewedDate,
                LastReferencedDate = dto.LastReferencedDate,
                AddressTypeCodeC = dto.AddressTypeCodeC,
                AdvisoryNoteIdentifierC = dto.AdvisoryNoteIdentifierC,
                CityC = dto.CityC,
                CompanyNameC = dto.CompanyNameC,
                ContactFirstNameC = dto.ContactFirstNameC,
                ContactLastNameC = dto.ContactLastNameC,
                ContactPhoneC = dto.ContactPhoneC,
                CountryC = dto.CountryC,
                DeliveryPriorityCodeC = dto.DeliveryPriorityCodeC,
                Iso2CharacterCountryCodeC = dto.Iso2CharacterCountryCodeC,
                LatitudeC = dto.LatitudeC,
                LegacyPartOrderNumberC = dto.LegacyPartOrderNumberC,
                LocationLatitudeS = dto.LocationLatitudeS,
                LocationLongitudeS = dto.LocationLongitudeS,
                LogisticOrderIdentifierC = dto.LogisticOrderIdentifierC,
                LongitudeC = dto.LongitudeC,
                OrderEstimatedArrivalTimeStampC = dto.OrderEstimatedArrivalTimeStampC,
                OrderReasonCodeC = dto.OrderReasonCodeC,
                OrderStatusCodeC = dto.OrderStatusCodeC,
                OrderTypeCodeIdentifierC = dto.OrderTypeCodeIdentifierC,
                PartDeliveryRequestedTimeStampC = dto.PartDeliveryRequestedTimeStampC,
                PartOrderIdentifierC = dto.PartOrderIdentifierC,
                PartOrderTypeCodeC = dto.PartOrderTypeCodeC,
                PartPickupLocationC = dto.PartPickupLocationC,
                PickPackInstructionsC = dto.PickPackInstructionsC,
                PickupTaskC = dto.PickupTaskC,
                PreferredLangugeCodeC = dto.PreferredLangugeCodeC,
                ReceivedInstructionsC = dto.ReceivedInstructionsC,
                RepairTaskC = dto.RepairTaskC,
                ResponsiblePartyIdC = dto.ResponsiblePartyIdC,
                SecurityStatusCodeC = dto.SecurityStatusCodeC,
                SentInstructionsC = dto.SentInstructionsC,
                ServiceNotificationIdentifierC = dto.ServiceNotificationIdentifierC,
                ShippingCarrierCodeC = dto.ShippingCarrierCodeC,
                ShippingConditionCodeC = dto.ShippingConditionCodeC,
                ShippingConditionUpgradeReasonCodeC = dto.ShippingConditionUpgradeReasonCodeC,
                SpecialDeliveryProcessCodeC = dto.SpecialDeliveryProcessCodeC,
                StateC = dto.StateC,
                Street2C = dto.Street2C,
                StreetC = dto.StreetC,
                TrunkStockIndicatorC = dto.TrunkStockIndicatorC,
                ZipPostalCodeC = dto.ZipPostalCodeC,
                AvailabilityCheckCompleteC = dto.AvailabilityCheckCompleteC,
                ServiceDeliveryTypeC = dto.ServiceDeliveryTypeC,
                PendingTransactionTypeC = dto.PendingTransactionTypeC,
                MessageC = dto.MessageC,
                MessageTypeC = dto.MessageTypeC,
                OrderPlacedInBcpC = dto.OrderPlacedInBcpC,
                CaseNumberC = dto.CaseNumberC,
                SkuC = dto.SkuC,
                AnyPartLineInJeopardyStatusC = dto.AnyPartLineInJeopardyStatusC,
                CalculatedArrivalTimeStampC = dto.CalculatedArrivalTimeStampC,
                PartTransferDestinationTaskC = dto.PartTransferDestinationTaskC,
                UpdateBadgeDestinationEngineerC = dto.UpdateBadgeDestinationEngineerC,
                SbdDeferredC = dto.SbdDeferredC,
                CrsIdC = dto.CrsIdC,
                MediaRetentionEligibilityC = dto.MediaRetentionEligibilityC,
                PrivateC = dto.PrivateC,
                DualDispatchC = dto.DualDispatchC,
                InsertGmtTimestamp = dto.InsertGmtTimestamp,
                Createdby = dto.Createdby,
                UpdatedGmtTimestamp = dto.UpdatedGmtTimestamp,
                Updatedby = dto.Updatedby,
                BadgeC = dto.BadgeC,
                PartsUsageLoggingCompleteC = dto.PartsUsageLoggingCompleteC,
                ContactEmailC = dto.ContactEmailC,
                TriggerAutomaticPartsOrderingC = dto.TriggerAutomaticPartsOrderingC,
                TriggerImmediatePartsOrderingC = dto.TriggerImmediatePartsOrderingC,
                PartLineCountC = dto.PartLineCountC,
                CountOfOpenPartLinesC = dto.CountOfOpenPartLinesC,
                ContactNameC = dto.ContactNameC,
                CountOfJeapodyPartLinesC = dto.CountOfJeapodyPartLinesC,
                TriggerCsrPartsUsageC = dto.TriggerCsrPartsUsageC,
                CountOfNonPodPartLinesC = dto.CountOfNonPodPartLinesC,
                RohsProductNumberC = dto.RohsProductNumberC,
                RohsOverrideC = dto.RohsOverrideC,
                IsRevisitOrderC = dto.IsRevisitOrderC,
                MissionCriticalC = dto.MissionCriticalC,
                CoverageResponseC = dto.CoverageResponseC,
                EntitlementSlaResponseC = dto.EntitlementSlaResponseC,
                RequestorTimeZoneC = dto.RequestorTimeZoneC,
                ModifierName = dto.ModifierName,
                ModifierValue = dto.ModifierValue,
                SerialNumber = dto.SerialNumber,
                ProductNumber = dto.ProductNumber,
                BcppartOrderId = dto.BcppartOrderId,
                BcpcaseNumber = dto.BcpcaseNumber,
                BcptaskId = dto.BcptaskId,
                OutageId = dto.OutageId,
                Region = dto.Region,
                ExpoPartOrderNumber = dto.ExpoPartOrderNumber,
                Cename = dto.Cename,
                Ceemail = dto.Ceemail,
                SfdcpartOrderId = dto.SfdcpartOrderId,
                SfdccaseNumber = dto.SfdccaseNumber,
                SfdctaskNumber = dto.SfdctaskNumber,
                CephoneNumber = dto.CephoneNumber
            }).ToList();
        }
    }
}
